name: Environment Variables
variables:
  - name: access_token
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTllNGIyNS1mYzg5LTc1ZDEtYmQzZi00Y2RhZTRkOTkwNTAiLCJleHAiOjE3NzkzOTMwMzMsImp0aSI6ImQzYmZiNmJjLWJiOTMtNGZhYy05YjYwLTE2NzA4Y2VmZDg2YyJ9.eP48ps5fuIzV4n_Z5Kaa8nMZYoLMMPvAiBnPDJKKBg0
  - name: refresh_token
    value: 8FAZ_VjupcpoXhWJ3h_dRZjbfj38jCTfiw7wVkSCbB0QnF4v6Xxwh9w4pRGV0idgJKDeHT8jzGW6BgTRGp4-yA
  - name: BASE_WS_URL
    value: ws://kim.netbird.cloud:3100/ws
  - name: BASE_HTTP_URL
    value: http://kim.netbird.cloud:3000
  - name: server_id
    value: e18e648e-24bb-4582-97dc-5f0e7b1e4e97
  - name: channel_id
    value: bbdb985a-e1ee-485e-87d0-6404fe2ddbe1
  - name: access_token2
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTllNGIyNi0yZDI5LTdiMjItYWMxMC1kNGNjYjRiMTE5NzAiLCJleHAiOjE3NzkzNzg2MTUsImp0aSI6IjkyZmM0MzRmLWI0ZTctNGY3Yi1iZWVlLWM2YWUyYmM1NTgxYSJ9.K-_fAlzHoFK55DZLfzIle_krPgqRauSjdV6zuyo_unc
  - name: refresh_token2
    value: ai3fXn-uDYn3rH4J5AtWb6n7WBONqcpAwZ-OYPoxm5HZH_vu1suQktfkWgacHAZv48_s3Zw3QavrniS07HtRWA
